### ISSUE TITLE
Meta/Chat link fading breaks poweruser flow

### ISSUE THREAD

**Issue by TuggyNE** [shu8/SE_OptionalFeatures#16]
Please remove the 500 ms fades from `show` and `hide` in `metaChatBlogStackExchangeButton`. When I hover to click, I have to consciously remember that the link's final location is not where it starts out, and misclicks are common. That's bad UX, and a fancy effect does not, to my mind, justify the continual rough edge it leaves in usability.

If you simply must have the cool fading, reduce it to maybe 50-100 ms. Either is still visible, but the window for misclicking is much smaller, and I don't think even I would have trouble.

**Comment by shu8** [comment]
Suppose that makes sense... done in 1.6 dev (which will be pushed to master **today** :)
