### ISSUE TITLE
KBD button alerts "click"; bullet button does not function

### ISSUE THREAD

**Issue by SnoringFrog** [shu8/SE_OptionalFeatures#19]
The kbd button sends a JS alert that says "click" every time it's clicked. That seems like something that never should have made it out of the dev branch. The list button would do the same thing, but it is currently broken (it's click event is bound to `#wmd-list-button` but it's actual id is `#wmd-bullet-button`).

**Comment by nwinkler** [comment]
The "click" alert has been fixed in #13, but it doesn't look like it was merged into the master branch yet.

**Comment by SnoringFrog** [comment]
I see that, but looks like they snuck back in shortly afterwards in 7e66807cf5c8d03e6042f92eec9a833dc89aadd4

**Comment by nwinkler** [comment]
True...

**Comment by shu8** [comment]
@SnoringFrog you're right... don't know how that happened :/ Thanks for #22 - I will see if that fixes everything, but if it's not too hard, would it be possible for you to change that pull request to target the `develop` branch please?

**Comment by shu8** [comment]
fixed in #24
