### ISSUE TITLE
Hot Question message not appearing

### ISSUE THREAD

**Issue by SnoringFrog** [shu8/SE_OptionalFeatures#20]
I can't seem to get the hot question message to appear. From the testing I've done, it seems that nothing in `preprocess` is being run. The rest of the `.feeds()` call works fine, but nothing I add to `preprocess` takes any effect, not sure why.

**Comment by shu8** [comment]
@SnoringFrog I will look into this -- but I'm away for the next 3 days and might not have time during the week -- but at the latest, I'll look at it by next weekend! :)

**Comment by SnoringFrog** [comment]
Gotcha. No rush (for me at least). It's probably one of the more minimal features, but I figured you'd want to know about the bug regardless. I tried looking into it some but couldn't make any headway on it.

**Comment by shu8** [comment]
Very weird... It seems `onComplete: function()` or `preprocess: function()` are just ignored.

I get the error `jQuery21409325341042131186_1443266418820 is not defined` because the response starts with `/* callback */jQuery214013556369650177658_1443266447976({"responseData" .... }):`.

**Comment by shu8** [comment]
btw @SnoringFrog SOOF is now SOX, and has moved to https://github.com/soscripted/sox. This feature is under consideration - we may remove it.

@Loxos and @nwinkler, you may also be interested in knowing that SOOF is now SOX, at https://github.com/soscripted/sox!! :)
