### ISSUE TITLE
Color the answerer's name in comments colours all answerers names on any answer

### ISSUE THREAD

**Issue by SnoringFrog** [shu8/SE_OptionalFeatures#26]
[This answer illustrates the issue](http://worldbuilding.stackexchange.com/a/25539/7951). 

**Youstay Igo** posted the answer, **Lord of Eden** posted the question. However, in the comments on **Youstay Igo**'s answer, both **Youstay Igo** and **Michael Richardson**'s names are colored. As it turns out, **Michael Richardson** posted one of the other answers to the question.

I didn't look into the code for this issue at all yet, so I'm not sure what the underlying problem might be.

**Comment by shu8** [comment]
@SnoringFrog That's what the feature's supposed to do: it colours all answerer's names in the comments...

**Comment by shu8** [comment]
(and as for your other issues - I'll look at them at the weekend! :)

**Comment by SnoringFrog** [comment]
Oh, gotcha. I thought it was only supposed to color their name on their own answers. My mistake then.

**Comment by shu8** [comment]
no problem! I find the current behaviour better because you can tell when someone who _has contributed_ something is saying something rather than those people who just say "this is wrong. you suck. I don't the know the answer, but blah blah blah" :P
