### ISSUE TITLE
Always shows the "Link from the web" box for images

### ISSUE THREAD

**Issue by SnoringFrog** [shu8/SE_OptionalFeatures#27]
Came across [this post on meta SO](http://meta.stackoverflow.com/a/306901/919057) today that seems like it'd fit well in this userscript. Not sure if you've used other people's scripts in the past or not, but figured it would be worth pointing out in case it was the type of thing you wanted to add. 

In short, it removes the need to click the "link from the web" link to display the text field to do so when uploading an image.

**Comment by shu8** [comment]
@SnoringFrog not a bad idea; don't know whether I'll use Siguza's script or make my own yet though...  :) Thanks for showing me this!

**Comment by shu8** [comment]
@SnoringFrog Let's see... http://meta.stackoverflow.com/questions/306888/change-image-upload-modal-to-always-show-url-input-field/306901#comment252628_306901 :)

**Comment by shu8** [comment]
@SnoringFrog the OP has let me use the code(!). So I will add it on the weekend. Thanks for this post again!

**Comment by shu8** [comment]
Done in v1.7 (currently in develop branch)!

Sorry for the extreme delay! :/
