### ISSUE TITLE
View/Remove Edit Reasons Popup

### ISSUE THREAD

**Issue by mezmi** [shu8/SE_OptionalFeatures#29]
I just installed the Tampermonkey script for the optional features and used the default settings.

I keep getting this popup everytime the page refreshes.

![editreasons](https://cloud.githubusercontent.com/assets/12533449/11016807/a2b39706-8540-11e5-8e54-dfceb7e01472.png)

~~I cannot find any documentation on this feature and~~ I've tried entering values but submitting them does nothing. I don't seem to be getting any errors in the console either.

**Comment by shu8** [comment]
Click reset at the top left - that should fix it :-)

If it does, please confirm so I can close this :)

**Comment by mezmi** [comment]
Yes, That did it.  

How would I go about adding more reasons? Am I going to have to edit script? If so, that's fine.

**Comment by shu8** [comment]
No - to add more reasons, go to the help button in the topbar and click 'Edit Reasons'.

BTW, if you're ever unsure on how to use a feature, the [readme file](https://github.com/shu8/SE_OptionalFeatures/blob/develop/README.md) has descriptions of all features at the bottom :) (but the 'reset' thing isn't mentioned on that - I might add that tho :/ )
