### ISSUE TITLE
Helpful Flag Percentage

### ISSUE THREAD

**Issue by mezmi** [shu8/SE_OptionalFeatures#37]
When viewing your flag history the overall percentage of your helpful flags is not displayed.

![flagging_history](https://cloud.githubusercontent.com/assets/12533449/11330743/4cfc87ba-9165-11e5-89c3-45015f7abe46.png)

Giving the user the ability to track their overall percentage would be _helpful_.
![flagging_history_improved](https://cloud.githubusercontent.com/assets/12533449/11330745/646fb1a6-9165-11e5-8bf6-013a4eb8209b.png)

Pending, Aged Away and [Disputed Flags](http://meta.stackexchange.com/a/95277/307724) are not counted in the total.

**Comment by mezmi** [comment]
@shu8 This is being [discussed on Meta](https://meta.stackoverflow.com/questions/310881/overall-percentage-of-helpful-flags) as a formal feature request.

**Comment by shu8** [comment]
nice. you have my +1 :)

I'll link to that in the readme soon... :)

**Comment by shu8** [comment]
(added to readme, slightly late! :/)
