### ISSUE TITLE
Synchronize Feature Changes Between Tabs

### ISSUE THREAD

**Issue by mezmi** [shu8/SE_OptionalFeatures#44]
As of right now if a feature is changed on one tab the changes are not reflected in any other open tabs.

Utilizing the [addValueChangeListener](https://tampermonkey.net/documentation.php#GM_addValueChangeListener) we can effectively synchronize feature changes between any open tabs.

I've added the following to the user script grants
`// @grant        GM_addValueChangeListener`

And added the following

<pre>
GM_addValueChangeListener("featureOptions", function () {
      console.log("SOOF Feature Options have changed, reloading page...");
      location.reload();
});
</pre>

I would also _suggest_ adding a confirm box to the Save Changes button in the features dialog that lets users know that Saving Changes could clear any questions or answers that have not automatically been saved as drafts. 

```
$('#submitOptions').click(function () {
    if (confirm("Saving Changes will sync them across all open tabs which might result in the loss of any questions or answers that have not been saved as drafts.")){
        var featureOptions = [];
        $('input[type=checkbox]:checked').each(function () {
            var x = $(this).attr('id');
            featureOptions.push(x); //Add the function's ID (also the checkbox's ID) to the array
        });
        GM_setValue('featureOptions', JSON.stringify(featureOptions)); //Save the setting
        console.log('Options saved: ' + featureOptions);
        $('#featureGMOptions').hide(500);
    }
});

GM_addValueChangeListener("featureOptions", function () {
    console.log("SOOF Feature Options have changed, reloading page to refresh styles");
    location.reload();
});
```

**Comment by shu8** [comment]
Firstly, thanks for the suggestion and pull request!

However, and please correct me if I'm wrong, it seems this is a new feature
that only exists on Tamper Monkey, and so will only work on Chrome.

It doesn't look like it will be a problem for FF users, but the feature
wouldn't exist for them :(

However, I will look at your pull request and probably accept it when I
have time.

Unfortunately though, I'm pretty busy till around mid-Jan, and might not do
anything till then!

**Comment by mezmi** [comment]
No problem! I'm not in any rush. 

I didn't realize that GreaseMonkey didn't have all the same API functions available, that's what I get for not looking at the docs. :(

Surely it could be done without that proprietary event listener just by polling the data for changes, maybe I'll look into doing that instead.

Happy Holidays.

**Comment by shu8** [comment]
Done!
