### ISSUE TITLE
Getting the leave page confirmation dialog when closing a tab after adding a comment

### ISSUE THREAD

**Issue by cullub** [shu8/SE_OptionalFeatures#46]
I originally thought it was a SO bug - so I [posted it there first](http://meta.stackoverflow.com/questions/316023/get-leave-page-confirmation-after-posting-comment).

Example:
![Animated GIF](https://cloud.githubusercontent.com/assets/7533931/12757392/783df6fa-c99d-11e5-92b5-71a34f46c359.gif)

**Comment by cullub** [comment]
FYI: Firefox Mac, 44.0
Not on Chrome or Safari.

**Comment by shu8** [comment]
@cullub whoops..! sorry for that :/

I'll look at this over the weekend and push a fix ASAP! I have a feeling it would be happening because it doesn't think the comment has been submitted and thinks there's still text in the box.

Till then, you may want to disable that feature.

Sorry again!

**Comment by shu8** [comment]
@cullub I've just looked at this and I cannot reproduce the bug. Is there anything else you do before entering+submitting a comment? Could you please check whether this still happens? (It may have been a random error caused by something else.) Thanks!

**Comment by cullub** [comment]
Nope, just tested it, and the same thing happens.  I just tested it on Chrome and Safari, and I can't reproduce it there - make sure you're using FF

**Comment by shu8** [comment]
@cullub hmm, you're right, I have no idea why it didn't happen to me before.

Anyway, I've changed it and added a fix in 1.8DEV. Please could you install [the 1.8dev version](https://github.com/shu8/Stack-Overflow-Optional-Features/raw/develop/features.user.js) and see if it's fixed for you?

Thanks!

**Comment by cullub** [comment]
Yeah, the 1.8dev fixes the problem.  I see you closed it already :+1:

**Comment by shu8** [comment]
:) yay! :P
