### ISSUE TITLE
Preview of linked post in blockquote extends past background

### ISSUE THREAD

**Issue by cullub** [shu8/SE_OptionalFeatures#48]
The preview of a linked post in a block-quote will extend past the right boundary of the yellow background.

Here's what I mean:

![screen shot 2016-02-06 at 9 22 30 am](https://cloud.githubusercontent.com/assets/7533931/12867452/d8b3f638-ccb3-11e5-8f16-2690dc49176c.png)

**Comment by cullub** [comment]
A minor issue, just FYI. This example is from [here](http://meta.stackoverflow.com/questions/316245/what-team-member-so-activity-should-we-gather-and-show-on-teams).

**Comment by shu8** [comment]
a slight CSS tweak will fix that:

```
    overflow-wrap: break-word;
    width: 630px;
    padding: 10px;
```

...should do.

Will push an update soon...

**Comment by cullub** [comment]
Awesome!  just close this and comment when you do.

**Comment by shu8** [comment]
done @cullub :)
