### ISSUE TITLE
Upvote temporarily hidden when scrolling down

### ISSUE THREAD

**Issue by cullub** [shu8/SE_OptionalFeatures#49]
It is currently possible (dev version) to have the upvote button (and even the vote count) hidden.

Example:

![screen shot 2016-02-06 at 9 44 29 am](https://cloud.githubusercontent.com/assets/7533931/12867580/a898da24-ccb6-11e5-8fc0-17b95cc11f81.png)

**Comment by shu8** [comment]
SOOF is now SOX, and has moved to https://github.com/soscripted/sox - please could you repost this there as well? Thanks!!
