### ISSUE TITLE
Conflict between 'Make the vote buttons sticky' and 'Make the topbar fixed'

### ISSUE THREAD

**Issue by shu8** [shu8/SE_OptionalFeatures#5]
I'm using v1.4 and I noticed that the following features seem to clash somehow:

Make the topbar fixed (stay at the top as you scroll)
Make the vote buttons sticky
The topbar stays at the top, that works fine, but when scrolling, the upvote button disappears under the topbar. See the following screenshot for an example:

![](http://i.stack.imgur.com/oLxRM.png)

It would be great if the upvote button was visible all the time.

(from http://stackapps.com/a/6450/26088)

**Comment by shu8** [comment]
I could add `margin-top: 34px;` to the vote buttons but that has the effect of making the vote button start 34px down than the usual place and looks ugly...

Anyone know a better way to fix this? :)

**Comment by nwinkler** [comment]
Good question...

The issue seems to be that the [sticky-element](https://github.com/EnzoMartin/Sticky-Element) plugin uses a container to stick the vote buttons to, and the topbar position is simply set to `fixed`.

Maybe it's possible to play with the position of the topbar, changing the size of the page so that the container starts right below the topbar, instead of under the topbar.

**Comment by shu8** [comment]
@nwinkler Thanks for replying (my first reply on GitHub! :D) 

This seems like a side-effect of fixing http://stackapps.com/a/6361/26088 - we ended up `fix`ing the position and _then_ pushing it back up - see the chat for details. 

I'll need to look into the container and see whether I can make it start a bit lower down - depending on where it is, it might not cause the vote buttons to start 34px down from the top of the post (I hope!)

**Comment by shu8** [comment]
@nwinkler @Loxos fixed this! :)

**Comment by nwinkler** [comment]
Great! When will this be available in `master`? Any plans for your next official release?

**Comment by shu8** [comment]
I'm away at the moment but I think I'll update it to master in the second
week of September! :)

On Thursday, 27 August 2015, Nils Winkler notifications@github.com wrote:

> Great! When will this be available in master? Any plans for your next
> official release?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shu8/SE_OptionalFeatures/issues/5#issuecomment-135365154
> .

## 

Sent from Gmail Mobile

**Comment by nwinkler** [comment]
Great, thanks for the update!
