### ISSUE TITLE
Comments shift left when vote dial switches to floating along the side of post

### ISSUE THREAD

**Issue by cullub** [shu8/SE_OptionalFeatures#50]
As you're scrolling down a page, it's nice to have the vote button on the side of the post, however, on shorter posts, you'll notice a minor bug: the comments will jump left about a half-inch, as soon as the vote toggle jumps down to be next to the post.

See example:

![bug](https://cloud.githubusercontent.com/assets/7533931/12867611/986778ee-ccb7-11e5-8562-fd542d60930a.gif)

**Comment by shu8** [comment]
@cullub SOOF is now SOX, and has moved to https://github.com/soscripted/sox. Would you mind reposting this there? thanks!
